version: "3"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
    networks:
      - levent

  php:
    build:
      context: .
      dockerfile: dockers/php/Dockerfile
    volumes:
      - "./src/l-event:/srv/app"
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_HOST: mysql
      APP_URL: http://localhost:8080
    networks:
      - levent

networks:
  levent:
